import { useState, useEffect, useRef } from "react";

// ── Data ──────────────────────────────────────────────────────────────────────
const COLLEGES = [
  {
    id: "iit-bombay",
    name: "IIT Bombay",
    location: "Mumbai, Maharashtra",
    stream: "Engineering",
    fees: "₹2.3L/yr",
    ranking: 1,
    nirf: 3,
    image: "🏛️",
    established: 1958,
    students: "11,000+",
    faculty: "600+",
    courses: ["B.Tech", "M.Tech", "PhD", "MBA"],
    highlights: ["Top NIRF Engineering", "Placement avg ₹20L+", "World-class labs"],
    cutoff: "JEE Advanced – Gen: 67 | OBC: 200 | SC: 350",
    placements: { avg: "₹21.8L", highest: "₹2.4Cr", companies: 500 },
    description:
      "IIT Bombay is among India's premier engineering institutes, known for cutting-edge research, top placements, and an elite alumni network spanning global tech companies.",
    color: "#0066CC",
  },
  {
    id: "bits-pilani",
    name: "BITS Pilani",
    location: "Pilani, Rajasthan",
    stream: "Engineering",
    fees: "₹5.2L/yr",
    ranking: 2,
    nirf: 25,
    image: "🎓",
    established: 1964,
    students: "15,000+",
    faculty: "900+",
    courses: ["B.E.", "M.E.", "M.Sc.", "MBA"],
    highlights: ["Autonomous curriculum", "Practice School Program", "Dual degree option"],
    cutoff: "BITSAT – Gen: 350+ | OBC: 320+ | SC: 280+",
    placements: { avg: "₹17.5L", highest: "₹1.8Cr", companies: 400 },
    description:
      "BITS Pilani is a deemed university renowned for academic freedom, its industry-integrated Practice School program, and consistently top placements across tech and finance.",
    color: "#CC0033",
  },
  {
    id: "aiims-delhi",
    name: "AIIMS New Delhi",
    location: "New Delhi",
    stream: "Medical",
    fees: "₹1.6K/yr",
    ranking: 1,
    nirf: 1,
    image: "🏥",
    established: 1956,
    students: "3,500+",
    faculty: "700+",
    courses: ["MBBS", "MD", "MS", "PhD", "BSc Nursing"],
    highlights: ["#1 Medical in India", "Central Govt institute", "World-class hospital"],
    cutoff: "NEET – Gen: 700+ | OBC: 690+ | SC: 650+",
    placements: { avg: "₹12L", highest: "₹60L", companies: 200 },
    description:
      "AIIMS New Delhi is India's most prestigious medical institution, offering unparalleled clinical training, research facilities, and access to thousands of patients for hands-on learning.",
    color: "#007755",
  },
  {
    id: "iim-ahmedabad",
    name: "IIM Ahmedabad",
    location: "Ahmedabad, Gujarat",
    stream: "Management",
    fees: "₹11.5L/yr",
    ranking: 1,
    nirf: 1,
    image: "💼",
    established: 1961,
    students: "1,200+",
    faculty: "100+",
    courses: ["PGP", "PGPX", "PhD", "Executive MBA"],
    highlights: ["#1 B-School in India", "Global alumni 40,000+", "Avg pkg ₹35L+"],
    cutoff: "CAT – Gen: 99%ile | OBC: 97%ile | SC: 90%ile",
    placements: { avg: "₹35.1L", highest: "₹1.1Cr", companies: 150 },
    description:
      "IIM Ahmedabad is Asia's top business school, known for its rigorous case-method pedagogy, exceptional faculty, and an alumni network that leads Fortune 500 companies globally.",
    color: "#AA3300",
  },
  {
    id: "nit-trichy",
    name: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    stream: "Engineering",
    fees: "₹1.8L/yr",
    ranking: 5,
    nirf: 8,
    image: "⚙️",
    established: 1964,
    students: "9,000+",
    faculty: "500+",
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    highlights: ["Top NIT nationally", "Strong South India network", "Excellent placements"],
    cutoff: "JEE Main – Gen: 5000 | OBC: 12000 | SC: 30000",
    placements: { avg: "₹12.4L", highest: "₹80L", companies: 350 },
    description:
      "NIT Trichy is consistently ranked among the top NITs in India, offering quality technical education, strong industry connections, and a vibrant campus life in Tamil Nadu.",
    color: "#5500AA",
  },
  {
    id: "du-delhi",
    name: "University of Delhi",
    location: "New Delhi",
    stream: "Arts & Science",
    fees: "₹25K/yr",
    ranking: 6,
    nirf: 11,
    image: "📚",
    established: 1922,
    students: "3,00,000+",
    faculty: "9,000+",
    courses: ["BA", "BSc", "BCom", "LLB", "MA", "PhD"],
    highlights: ["84 premier colleges", "Largest central univ", "Legacy since 1922"],
    cutoff: "CUET – Gen: 95%+ | OBC: 90%+ | SC: 82%+",
    placements: { avg: "₹6.5L", highest: "₹40L", companies: 600 },
    description:
      "University of Delhi is one of India's largest and most prestigious universities, encompassing 84 colleges across humanities, sciences, commerce, and law with a storied 100-year legacy.",
    color: "#0044AA",
  },
];

const TESTIMONIALS = [
  { name: "Ananya Sharma", college: "IIT Delhi – CSE", exam: "JEE Advanced", rank: 847, text: "CollegeCompass's Rank Predictor was spot-on! I knew exactly which branches to target and got my dream branch. The counselling team guided me through every step.", avatar: "A", score: "AIR 847" },
  { name: "Rohan Mehta", college: "IIM Bangalore – PGP", exam: "CAT", rank: 99.4, text: "The MBA counselling sessions were a game changer. The counsellors had inside knowledge about interview processes at top IIMs that I couldn't find anywhere else.", avatar: "R", score: "99.4%ile" },
  { name: "Priya Nair", college: "AIIMS New Delhi – MBBS", exam: "NEET", rank: 312, text: "As a student from Kerala, I had no idea how to navigate NEET counselling for all-India seats. CollegeCompass made the entire process crystal clear. Forever grateful!", avatar: "P", score: "AIR 312" },
  { name: "Karthik Subramaniam", college: "NIT Warangal – ECE", exam: "JEE Main", rank: 4200, text: "I was confused between 5 NITs. The College Comparison Tool helped me evaluate placements, campus life and fees side by side. Best decision I ever made.", avatar: "K", score: "AIR 4200" },
  { name: "Sneha Gupta", college: "BITS Pilani – CS", exam: "BITSAT", rank: 98, text: "The scholarship finder found ₹1.2L in scholarships I had no idea I was eligible for. The virtual tour of BITS convinced me this was my place!", avatar: "S", score: "BITSAT 371" },
  { name: "Aditya Kumar", college: "IIT Madras – Mech", exam: "JEE Advanced", rank: 1240, text: "Moved from Bihar to Chennai for IIT Madras. CollegeCompass's hostel and campus info prepared me perfectly. The placement data was accurate to the last decimal.", avatar: "A", score: "AIR 1240" },
];
